# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.24
source:
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
    - pcre2-compat.patch
  sha256: 62743265222a729c7fe94c40f7b90ccc1ac5568f5ee6df46884e7ce3c16c78c7
  url: https://github.com/openSUSE/libsolv/archive/0.7.24.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '1'
  script: install.sh
  string: he621ea3_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - bzip2 1.0.8 h5eee18b_5
    - c-ares 1.19.1 h5eee18b_0
    - ca-certificates 2024.3.11 h06a4308_0
    - cmake 3.26.4 h96355d8_0
    - expat 2.6.2 h6a678d5_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.20.1 h143b758_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libcurl 8.5.0 h251f7ec_0
    - libedit 3.1.20230828 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.57.0 h2d74bed_0
    - libssh2 1.10.0 hdbd6064_2
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libuv 1.44.2 h5eee18b_0
    - lz4-c 1.9.4 h6a678d5_0
    - ncurses 6.4 h6a678d5_0
    - ninja 1.10.2 h06a4308_5
    - ninja-base 1.10.2 hd09550d_5
    - openssl 3.0.13 h7f8727e_0
    - python 3.12.3 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - rhash 1.4.3 hdbd6064_0
    - sqlite 3.41.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
    - zstd 1.5.5 hc292b87_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_5
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - pcre2 10.42 hebb0a14_0
    - pkg-config 0.29.2 h1bed415_8
    - zlib 1.2.13 h5eee18b_0
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - pcre2 >=10.42,<10.43.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libsolv${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsolvext${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsolv.so.1
    - test -f ${PREFIX}/include/solv/repo.h
    - dumpsolv -h
about:
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.

    '
  dev_url: https://github.com/openSUSE/libsolv
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 085ad689-a617-46a0-ab2d-c00b949dacd6
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/libsolv-feedstock.git
  sha: 5c95f2e772e6082682ca6b3d68b33fca382c991d
