# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Sep 12 18:16:05 2024
# ------------------------------------------------

package:
  name: wheel
  version: 0.44.0
source:
  sha256: a29c3f2817e95ab89aa4660681ad547c0e9547f20e75b0562fe7723c9a2a9d49
  url: https://pypi.io/packages/source/w/wheel/wheel-0.44.0.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.7.2 h06a4308_0
    - flit-core 3.9.0 py310hee27c6d_1
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - python 3.10.14 h955ad1f_1
    - python-installer 0.7.0 py310h06a4308_0
    - readline 8.2 h5eee18b_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: dea600d5-171a-46d8-accb-7225f884f295
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/wheel-feedstock.git
  sha: 0ac31e00904848003b64917d8d0cf8946fcd3f3f
  skip-lints:
    - missing_wheel
